package net.laylacp.pdflib.core.types;

public enum TokenType {
    TOKEN_WHITESPACE,
    TOKEN_LT_PAREN,
    TOKEN_RT_PAREN,
    TOKEN_LESS_THAN,
    TOKEN_GREATER_THAN,
    TOKEN_LT_BRACKET,
    TOKEN_RT_BRACKET,
    TOKEN_LT_CURLY,
    TOKEN_RT_CURLY,
    TOKEN_SOLIDUS,
    TOKEN_PERCENT,

    TOKEN_NAME_OBJECT,
    TOKEN_UNKOWN_WORD,
    TOKEN_DBL_LESS_THAN,
    TOKEN_DBL_GREATER_THAN,

    TOKEN_EOF,
}
